"""Create optimized_products table

Revision ID: 68dd5bc9f6ba
Revises: 1c5d65447d15
Create Date: 2025-09-03 11:06:09.227853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dd5bc9f6ba'
down_revision: Union[str, Sequence[str], None] = '1c5d65447d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimized_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('shopify_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['original_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimized_products_id'), 'optimized_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimized_products_id'), table_name='optimized_products')
    op.drop_table('optimized_products')
    # ### end Alembic commands ###
