import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';

const ProductInsightsPage: React.FC = () => {
  const { productId } = useParams<{ productId: string }>();
  const [insights, setInsights] = useState<any>(null);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        setLoading(true);
        // This endpoint will fetch the insights generated by the backend
        const response = await axios.get(`http://localhost:8000/api/product-insights/${productId}`);
        setInsights(response.data);
      } catch (err) {
        setError('Failed to fetch product insights.');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    if (productId) {
      fetchInsights();
    }
  }, [productId]);

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center">
        Loading product insights...
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex h-screen items-center justify-center text-red-500">
        Error: {error}
      </div>
    );
  }

  if (!insights) {
    return (
      <div className="flex h-screen items-center justify-center">
        No insights found for this product.
      </div>
    );
  }

  return (
    <div className="bg-white p-6 rounded-lg shadow-md">
      <h1 className="text-2xl font-bold mb-4">Insights for Product ID: {productId}</h1>
      <pre className="bg-gray-100 p-4 rounded-md overflow-auto">
        {JSON.stringify(insights, null, 2)}
      </pre>
      {/* You can render the insights in a more user-friendly way here */}
    </div>
  );
};

export default ProductInsightsPage;
